### ISSUE TITLE
Any updates on this?

### ISSUE THREAD

**Issue by lghamie** [eltrino/diamantedesk-docker#1]
Will this go unmantained?

**Comment by odi-um** [comment]
hi @lghamie, we will update it during this week.

**Comment by lghamie** [comment]
Great, such good news!

**Comment by lghamie** [comment]
Hi guys, could you work on this? 

Thanks!

**Comment by krasilich** [comment]
@lghamie Please check updated doc. Also note that previous docker repository is deprecated now, and that image will be deleted soon, please use new one https://hub.docker.com/r/eltrino/diamantedesk/

Thank you.

**Comment by lghamie** [comment]
Thanks a lot!!!
